FROM node:22-alpine AS build

WORKDIR /app

COPY . .

RUN npm ci
RUN npm --workspace @catering/backoffice-ui run build

FROM nginx:1.27-alpine

COPY platform-infra/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/backoffice-ui/dist /usr/share/nginx/html
