import type { OfferWorkbenchProps } from "./offer-workbench.js";

export type OfferWorkbenchStateInput = OfferWorkbenchProps;

export function buildOfferWorkbenchState({
  submitting,
  latestSourceLabel,
  offerText,
  setOfferText,
  submitOfferText,
  intakeText,
  setIntakeText,
  submitIntakeText,
  intakeChannel,
  setIntakeChannel,
  intakeFile,
  setIntakeFile,
  submitIntakeDocument,
  manualInput,
  manualActions,
  filteredOfferDrafts,
  activeDraft,
  selectedDraft,
  setSelectedDraftId,
  selectedVariantId,
  setSelectedVariantId,
  approveDraft,
  approvalBinding,
  createHandoff,
  filteredSpecs,
  activeSpec,
  completeSpecCount,
  partialSpecCount,
  miniPilotRawResult,
  setMiniPilotRawResult,
  miniPilotReportState,
  miniPilotStorageHintLabel,
  specEdit,
  specEditActions
}: OfferWorkbenchStateInput): OfferWorkbenchProps {
  return {
    submitting,
    latestSourceLabel,
    offerText,
    setOfferText,
    submitOfferText,
    intakeText,
    setIntakeText,
    submitIntakeText,
    intakeChannel,
    setIntakeChannel,
    intakeFile,
    setIntakeFile,
    submitIntakeDocument,
    manualInput,
    manualActions,
    filteredOfferDrafts,
    activeDraft,
    selectedDraft,
    setSelectedDraftId,
    selectedVariantId,
    setSelectedVariantId,
    approveDraft,
    approvalBinding,
    createHandoff,
    filteredSpecs,
    activeSpec,
    completeSpecCount,
    partialSpecCount,
    miniPilotRawResult,
    setMiniPilotRawResult,
    miniPilotReportState,
    miniPilotStorageHintLabel,
    specEdit,
    specEditActions
  };
}
